# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  ENV["CERTIFICATE_PASSWORD"] = "chimo888"
  ENV["KEYCHAIN_NAME"] = "temporary_keychain"
  ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "bgbc-edin-hbln-anyh"
  ENV["SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER"] = "+56959312752"
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "RnFeaturesNews.xcodeproj")
    create_temporary_keychain
    #setup_jenkins(
    #  force: true
    #) 
    match(
      type: "appstore",
      git_url: "git@bitbucket.org:jacm80/rn186storekeys.git",
      clone_branch_directly: true,
      verbose: true,
      username: "jacanepa@gmail.com"
    )
    # match(
    #   type: "appstore",
    #   git_url: "https://jacm80@bitbucket.org/jacm80/rn186storekeys.git"
    # )
    build_app(
      scheme: "RnFeaturesNews",
      export_options: {
        method: "appstore",
      }
    )
    upload_to_testflight

    if options[:use_temporary_keychain]
      sh "security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k #{ENV["KEYCHAIN_NAME"]} #{ENV["KEYCHAIN_PASSWORD"]}"
    end
  end
end

private_lane :create_temporary_keychain do
  keychain_name = "temporary_keychain"
  ENV["KEYCHAIN_NAME"] = keychain_name
  ENV["KEYCHAIN_PASSWORD"] = keychain_name
  ENV["MATCH_KEYCHAIN_NAME"] = keychain_name 
  ENV["MATCH_KEYCHAIN_PASSWORD"] = keychain_name

  create_keychain(
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    add_to_search_list: true
  )
end